arch:
- aarch64
- amd64
- armhf
- armv7
- i386
description: Mictronics' readsb-protobuf Mode-S/ADSB/TIS decoder for RTLSDR, BladeRF, Modes-Beast and GNS5894 devices.
image: mikenye/readsb-protobuf:v4.0.2_nohealthcheck/{arch}
ingress: true
ingress_stream: true
map:
- share:rw
name: readadsb
panel_icon: mdi:radar
panel_title: readadsb
ports:
  8080/tcp: 9000
  30005/tcp: 30005
ports_description:
  8080/tcp: Web management
  30005/tcp: Mode-S network traffic
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
slug: readsb
startup: application
uart: true
udev: true
url: https://github.com/libby2cm/hass-addons/readsb
version: 0.1.0
